#!/usr/bin/env bash
# Deploy the RINGO web client to S3 + CloudFront.
#   ./scripts/deploy-web.sh
set -euo pipefail
cd "$(dirname "$0")/.."

BUCKET=ringo-web-352154386127-us-east-2
DIST_ID=E18D1UE8BFITPD
WS_URL=wss://4bwxqaz8cj.execute-api.us-east-2.amazonaws.com/prod

BUILD=build/web
rm -rf "$BUILD"
mkdir -p "$BUILD"
cp -r public/* "$BUILD/"

# Production config: point online play at the API Gateway WebSocket endpoint.
cat > "$BUILD/js/config.js" <<EOF
// Generated by scripts/deploy-web.sh — do not edit by hand.
window.RINGO_WS_URL = '$WS_URL';
EOF

aws s3 sync "$BUILD/" "s3://$BUCKET/" --delete
aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths '/*' \
  --query 'Invalidation.Id' --output text
echo "Deployed → https://ringo.beelinemicrosystems.com"
